[application]
assets_dir = "assets"

[components]
components_dir = "src/components/ui"

[web.app]

# HTML title tag content
title = "bestofrs"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[web.wasm_opt]
level = "0"
